apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-tekton
  namespace: argocd
spec:
  destination:
    namespace: basic-spring-boot-cicd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: .
    repoURL: 'https://github.com/paolocarta/tekton-helm-pipeline.git'
    targetRevision: master