apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: basic-spring-boot-deploy-pipeline-run
spec:
  pipelineRef:
    name: basic-spring-boot-deploy-only-pipeline
  resources:
  - name: basic-spring-boot-templates
    resourceRef:
      name: basic-spring-boot-templates
  serviceAccountName: pipeline
  timeout: 1h0m0s