apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: {{ include "springboot-tekton.fullname" . }}-first-pipe-run
spec:
  pipelineRef:
    name: {{ include "springboot-tekton.fullname" . }}-pipeline
  resources:
  - name: {{ include "springboot-tekton.fullname" . }}-git
    resourceRef:
      name: {{ include "springboot-tekton.fullname" . }}-git-first-run
  - name: {{ include "springboot-tekton.fullname" . }}-templates
    resourceRef:
      name: {{ include "springboot-tekton.fullname" . }}-templates-first-run
  - name: {{ include "springboot-tekton.fullname" . }}-image
    resourceRef:
      name: {{ include "springboot-tekton.fullname" . }}-image
  serviceAccountName: {{ .Values.serviceAccount.name }}
  workspaces:
  - name: local-maven-repo
    persistentVolumeClaim:
      claimName: maven-repo-pvc-2
  timeout: 1h0m0s